name: Run productos scraper

on:
  schedule:
    - cron: '*/15 * * * *'  # cada 15 minutos (UTC)
  workflow_dispatch:        # permite ejecutarlo manualmente desde GitHub

jobs:
  run-productos-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright and deps
        run: |
          npx playwright install --with-deps

      - name: Run productos.js
        run: node productos.js
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
          SHEET_ID: ${{ secrets.SHEET_ID }}

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 1,
              body: "⚠️ El scraper de productos falló. Verificá el workflow: https://github.com/${context.repo.owner}/${context.repo.repo}/actions"
            })
