name: Run scraper manually

on:
  workflow_dispatch:


jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright and deps
        run: |
          npx playwright install --with-deps

      - name: Run script
        run: node index.js
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
          SHEET_ID: ${{ secrets.SHEET_ID }}

      - name: Upload screenshot
          uses: actions/upload-artifact@v4
          with:
          name: login-screenshot
          path: screenshot_login.png

