name: Run scraper daily

on:
  schedule:
    - cron: '0 7 * * *' # todos los días a las 04:00 AM Argentina (07:00 UTC)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright and deps
        run: |
          npx playwright install --with-deps

      - name: Run script
        run: node index.js
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
          SHEET_ID: ${{ secrets.SHEET_ID }}

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 1,
              body: "⚠️ El scraper falló hoy a las 04:00 AM. Verificá el workflow para más info: https://github.com/${context.repo.owner}/${context.repo.repo}/actions"
            })
